GET http://localhost:3000/tasks


###

GET http://localhost:3000/tasks/607674fd2003793524b7a1a0

###

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name": "william",
    "taskTitle": "morning routine",
    "taskDescription": "this will list out all the activities I need to do in the morning",
    "subTasks":{
        "subTasksID":"1",
        "subTasksName":"",
        "subTasksDescription":"",
        "subTasksChecked": false
    }
}